"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import configparser
import os

# --------------------------------------------------
# Base directory
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# Load secrets file
# --------------------------------------------------
SECRETS_FILE = BASE_DIR / ".secrets"

config = configparser.ConfigParser()

if not SECRETS_FILE.exists():
    raise FileNotFoundError(f".secrets file not found at {SECRETS_FILE}")

config.read(SECRETS_FILE)


def get_secret(section, key, fallback=None, required=True):
    """
    Safely fetch secrets from .secrets file
    """
    try:
        return config.get(section, key, fallback=fallback)
    except (configparser.NoSectionError, configparser.NoOptionError):
        if required:
            raise Exception(f"Missing required secret: [{section}] {key}")
        return fallback


def get_secret_bool(section, key, fallback=False):
    try:
        return config.getboolean(section, key, fallback=fallback)
    except ValueError:
        raise Exception(f"Invalid boolean value for [{section}] {key}")


# --------------------------------------------------
# SECURITY SETTINGS
# --------------------------------------------------

SECRET_KEY = get_secret("django", "SECRET_KEY")

DEBUG = get_secret_bool("django", "DEBUG", fallback=False)

ALLOWED_HOSTS = config.get("django", "ALLOWED_HOSTS", fallback="").split(",")


# --------------------------------------------------
# Application definition
# --------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "rest_framework",
    "tickets",
    "corsheaders",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# --------------------------------------------------
# DATABASE CONFIGURATION
# --------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": get_secret("database", "ENGINE"),
        "NAME": get_secret("database", "NAME"),
        "USER": get_secret("database", "USER"),
        "PASSWORD": get_secret("database", "PASSWORD", fallback=""),
        "HOST": get_secret("database", "HOST"),
        "PORT": get_secret("database", "PORT"),
    }
}


# --------------------------------------------------
# Password validation
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# --------------------------------------------------
# Internationalization
# --------------------------------------------------

LANGUAGE_CODE = get_secret("django", "LANGUAGE_CODE", fallback="en-us")

TIME_ZONE = get_secret("django", "TIME_ZONE", fallback="UTC")

USE_I18N = True

USE_TZ = True


# --------------------------------------------------
# Static files
# --------------------------------------------------

STATIC_URL = "static/"


# --------------------------------------------------
# Default primary key field type
# --------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True